default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: heliodor_development

test:
  <<: *default
  database: heliodor_test

production:
  <<: *default
  database: heliodor_production
  url: <%= ENV['DATABASE_URL'] %>
  username: heliodor
  password: <%= ENV['HELIODOR_DATABASE_PASSWORD'] %>
