# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: sqlite3
  <<: *default
  database: db/development.sqlite3

test:
  adapter: sqlite3
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  <<: *default
  database: heliodor_production
